spring:
  # redis 配置
  redis:
    # 地址
    host: 192.168.232.128
    # 端口，默认为6379
    port: 6379
    # 密码，没有不填
#    password: ''
    # 连接超时时cd
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
